name: Deploy Bot

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file available in docker
        run: |
          echo "BOT_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
          echo "GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}" >> .env
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> .env
          # Ticket Config
          echo "TICKET_CATEGORY_ID=${{ secrets.TICKET_CATEGORY_ID }}" >> .env
          echo "ARCHIVE_CATEGORY_ID=${{ secrets.ARCHIVE_CATEGORY_ID }}" >> .env
          echo "LOG_CHANNEL_ID=${{ secrets.LOG_CHANNEL_ID }}" >> .env
          echo "ADMIN_ROLE_ID=${{ secrets.ADMIN_ROLE_ID }}" >> .env
          # Account Config
          echo "ACCOUNT_BANK=${{ secrets.ACCOUNT_BANK }}" >> .env
          echo "ACCOUNT_NUMBER=${{ secrets.ACCOUNT_NUMBER }}" >> .env
          echo "ACCOUNT_OWNER=${{ secrets.ACCOUNT_OWNER }}" >> .env
          # AI Config
          echo "GEMINI_KEY=${{ secrets.GEMINI_KEY }}" >> .env

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Deploy to Dockge Path
        run: |
          sudo mkdir -p /opt/stacks/acog-bot
          
          sudo cp -r . /opt/stacks/acog-bot/
          
          sudo chown -R $USER:$USER /opt/stacks/acog-bot
          
          cd /opt/stacks/acog-bot
          docker compose down || true
          docker compose up -d --build
          
          docker image prune -f